# Example configuration file for Secure Cell Vault
# Copy this file to config.yaml and adjust the values

# Project Information
PROJECT_NAME: "Secure Cell Vault"
VERSION: "0.1.0"

# Security Settings
SECRET_KEY: "generate_a_secure_random_key_here"  # Change this!
ALGORITHM: "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES: 30
REFRESH_TOKEN_EXPIRE_DAYS: 7
PASSWORD_MIN_LENGTH: 12
BCRYPT_ROUNDS: 12

# Database Configuration
POSTGRES_SERVER: "localhost"
POSTGRES_USER: "secure_cell_vault"
POSTGRES_PASSWORD: "change_this_password"  # Change this!
POSTGRES_DB: "secure_cell_vault"

# Redis Configuration
REDIS_HOST: "localhost"
REDIS_PORT: 6379
REDIS_PASSWORD: "change_this_password"  # Change this!
REDIS_DB: 0

# Cell Configuration
DEFAULT_CELL_ROTATION_DAYS: 30
MIN_KEY_LENGTH: 32
MAX_SECRETS_PER_CELL: 1000

# HSM Configuration
USE_HSM: false
HSM_PROVIDER: null  # "aws", "azure", or "gcp"
HSM_CONFIG:
  # AWS Example:
  # region: "us-east-1"
  # key_id: "your-kms-key-id"
  
  # Azure Example:
  # vault_url: "https://your-vault.vault.azure.net"
  # key_name: "your-key-name"
  
  # GCP Example:
  # project_id: "your-project"
  # location: "global"
  # key_ring: "your-keyring"
  # key_name: "your-key"

# Audit Configuration
AUDIT_LOG_PATH: "logs/audit.log"
STRUCTURED_LOGGING: true
LOG_LEVEL: "INFO"

# Rate Limiting
RATE_LIMIT_PER_MINUTE: 100
RATE_LIMIT_BURST: 200

# CORS Settings
CORS_ORIGINS:
  - "http://localhost:3000"
  - "https://your-frontend-domain.com"
CORS_ALLOW_CREDENTIALS: true

# Authentication Settings
MFA_REQUIRED: true
SESSION_DURATION_MINUTES: 60
FAILED_LOGIN_DELAY: 3
MAX_FAILED_ATTEMPTS: 5
LOCKOUT_DURATION_MINUTES: 15

# API Security
MAX_REQUEST_SIZE_MB: 10
REQUEST_TIMEOUT_SECONDS: 30

# Backup Configuration
BACKUP_ENABLED: true
BACKUP_INTERVAL_HOURS: 24
BACKUP_RETENTION_DAYS: 30
BACKUP_ENCRYPTION_KEY: null  # Set this for encrypted backups

# Monitoring Configuration
ENABLE_METRICS: true
METRICS_PORT: 9090
HEALTH_CHECK_INTERVAL: 60